import {Container, Card, Row, Text, Grid, Input} from '@nextui-org/react'
import Head from 'next/head'
import React from 'react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid.Container fluid justify="center">
        <Grid>
          <Input
            rounded
            bordered
            label="Search site"
            placeholder="google.com"
            color="default"
          />
        </Grid>
      </Grid.Container>

      <Container lg>
          <Input
            rounded
            bordered
            label="Search site"
            placeholder="google.com"
            color="default"
          />
        <Card>
          <Card.Body>
            <Row justify="center" align="center">
              <Text h6 size={15}>
                NextUI gives you the best developer experience with all the features
                you need for building beautiful and modern websites and
                applications.
              </Text>
            </Row>
          </Card.Body>
        </Card>
      </Container>
    </>
  )
}
